### PR TITLE
Avoid calling close listeners when list is locked to avoid deadlocks

### PR DESCRIPTION
**Pull request by andrelanka**
See https://github.com/javaee/grizzly/issues/1983 for description of the problem

### CODE REVIEW

**Comment by rlubke** [comment]
Before any pull request can be accepted, the Oracle OCA must be signed and submitted.  See: https://github.com/javaee/grizzly/blob/master/CONTRIBUTING.md

**Comment by andrelanka** [comment]
Is sent the OCA to the oracle-ca_us [at] oracle [dot] com a week ago. Is there anything more to do?

**Comment by carryel** [comment]
@andrelanka I made another PR(https://github.com/javaee/grizzly/pull/1989) using concurrent collection without synchronized block. Before #1962 original code used ConcurrentLinkedQueue. What do you think about https://github.com/javaee/grizzly/pull/1989?

**Comment by andrelanka** [comment]
@carryel I also had `CopyOnWriteArrayList` in my mind, but I see some potential issues. I explained it in detail in the comment to you commit.

**Comment by rlubke** [comment]
I'm checking on the status of the OCA.  Will follow up as soon as I have confirmation.

**Pull request merged**
